server:
  port: 8100

spring:
  application:
    name: ZNTC-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          # 默认false, true: 开启通过服务中心的自动根据 serviceId 创建路由的功能
          enabled: false
      routes:
      - id: ZNTC-CAR
        # 重点！/info必须使用http进行转发，lb代表从注册中心获取服务
        uri: lb://ZNTC-CAR
        predicates:
          # 重点！转发该路径！,/api-car/**,
          - Path=/api-car/**
        # 过滤器
        filters:
          - StripPrefix=1 # 必须加上StripPrefix=1，否则访问服务时会带上api-car
          - AddResponseHeader=X-Response-Default-Foo, Default-Bar

      - id: ZNTC-ADMIN
        uri: lb://ZNTC-ADMIN
        predicates:
          - Path=/api-c/**
        filters:
          - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:1234@localhost:8000/eureka/

#gateway:
#  routes:
#    api-c:
#      path: /api-c/**
#      serviceId: ZNTC-ADMIN
#    api-user:
#      path: /api-user/**
#      serviceId: ZNTC-USER
